apiVersion: apps/v1
kind: Deployment
metadata:
  name: chouffe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chouffe
  template:
    metadata:
      labels:
        app: chouffe
    spec:
      containers:
        - name: chouffe
          image: funathonduvel/chouffe:latest
          env:
            - name: TEST
              value: 'true'
