apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: funathon-viz
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - url
  rules:
    - host: url
      http:
        paths:
          - path: /
            backend:
              serviceName: funathon-viz
              servicePort: http
